name: Nix CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Run CI checks
        run: |
          nix develop --command bash -c "
            npm ci
            npm run lint
            npm run build
          "
